stages:
  - test

webhook-test:
  stage: test
  image: alpine:3.20
  script:
    - echo "GitHub successfully triggered into GitLab!"
    - echo "Commit: $CI_COMMIT_SHA"
    - echo "Branch: $CI_COMMIT_REF_NAME"