spring.application.name=alumni-connect

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.flyway.clean-on-validation-error=false
spring.flyway.clean-disabled=true

# HikariCP
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:20}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:5}

# Disabled normally
spring.datasource.hikari.leak-detection-threshold=0

logging.level.com.zaxxer.hikari=INFO

# Server
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false

# LLM
llm.provider=${LLM_PROVIDER:llama}

# Gemini
gemini.api.key=${GEMINI_API_KEY:}

gemini.api.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent

# Llama / Ollama
llm.llama.url=${LLM_LLAMA_URL:http://host.docker.internal:11434/api/generate}
llm.llama.model=${LLM_LLAMA_MODEL:gemma3:1b}
llm.llama.timeout=${LLM_LLAMA_TIMEOUT:45s}

# Resilience4j
resilience4j.circuitbreaker.instances.llmService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.llmService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.llmService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.llmService.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.llmService.permittedNumberOfCallsInHalfOpenState=3

# Actuator7
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.metrics.export.simple.enabled=true 
